import { build } from "esbuild";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";

const manifest = JSON.parse(await readFile("public/data/manifest.json", "utf8"));
for (const [name, expected] of Object.entries(manifest.source_hashes ?? {})) {
  const bytes = await readFile(`../${name}`);
  if (createHash("sha256").update(bytes).digest("hex") !== expected) {
    throw new Error(`Scientific source ${name} changed. Run the pinned Python asset exporter with --fixtures before building.`);
  }
}
await writeFile(
  "src/lib/data-version.ts",
  `// Generated by scripts/build-worker.mjs\nexport const DATA_VERSION = ${JSON.stringify(manifest.version)};\n`,
);

const result = await build({
  entryPoints: ["src/lib/analysis/worker.ts"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  write: false,
});
const contents = result.outputFiles[0].contents;
const hash = createHash("sha256").update(contents).digest("hex").slice(0, 16);
const workerName = `analysis-${hash}.js`;
await mkdir("public/workers", { recursive: true });
for (const name of await readdir("public/workers")) {
  if (name.startsWith("analysis-") && name !== workerName) {
    await rm(`public/workers/${name}`);
  }
}
await writeFile(`public/workers/${workerName}`, contents);
await writeFile(
  "src/lib/worker-path.ts",
  `// Generated by scripts/build-worker.mjs\nexport const WORKER_PATH = "/workers/analysis-${hash}.js";\n`,
);
